apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-backend
  labels:
    app: express-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: express-backend
  template:
    metadata:
      labels:
        app: express-backend
    spec:
      containers:
      - name: express-backend
        image: sonupd8294/express-backend:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: express-backend-service
spec:
  type: ClusterIP
  selector:
    app: express-backend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
