apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-frontend
  labels:
    app: flask-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-frontend
  template:
    metadata:
      labels:
        app: flask-frontend
    spec:
      containers:
      - name: flask-frontend
        image: sonupd8294/flask-frontend:latest
        ports:
        - containerPort: 5000
        env:
        - name: BACKEND_URL
          value: "http://express-backend-service:3000"
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: flask-frontend-service
spec:
  type: NodePort
  selector:
    app: flask-frontend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30000
